### ISSUE TITLE
Shutdown/Reboot Interval

### ISSUE THREAD

**Issue by moriel5** [arteeh/pinetime#1]
You mentioned that watches are rarely rebooted, and while this isn't exactly the same, I can say that I try to shutdown my PineTime one a week, and also before some of my religion's holidays, due to me not wanting anything to activate the watch while on my wrist (laws pertaining to my religion), so I do not wear it then, and I'd rather save battery life when I am not using it at all.

The same goes for my phone and PCs (both laptop and desktop), as well as other electronics.

**Comment by arteeh** [comment]
I see. I think InfiniTime is working on storing their settings in the external flash, meaning data will persist across reboots. Once support for external flash / filesystem exists, storing settings is easy.
